package ge.ai.domino.domain.p2p;

public enum Command {

    GET_GAME_PROPERTIES,
    CAN_NOT_LISTEN_PLAY_COMMAND,
    CAN_LISTEN_PLAY_COMMAND,
    PLAY,
    GET_RANDOM_TILE,
    GET_RANDOM_TILE_ADDITIONAL_TRY,
    GET_GAME_BEGINNER,
    RESET_GAME_DATA_BAZAAR,
    RESET_GAME_DATA_OPPONENT_TILES,
    GET_OPPONENT_TILES,
    FINISH
}
