INSERT INTO arg_and_value (function_name, arg, value)
VALUES ('opponentPlayHeuristicsDiffsFunction', 500, 0.9999),
        ('opponentPlayHeuristicsDiffsFunction', 100, 0.99),
        ('opponentPlayHeuristicsDiffsFunction', 50, 0.97),
        ('opponentPlayHeuristicsDiffsFunction', 40, 0.95),
        ('opponentPlayHeuristicsDiffsFunction', 30, 0.92),
        ('opponentPlayHeuristicsDiffsFunction', 20, 0.85),
        ('opponentPlayHeuristicsDiffsFunction', 15, 0.8),
        ('opponentPlayHeuristicsDiffsFunction', 10, 0.6),
        ('opponentPlayHeuristicsDiffsFunction', 5, 0.4),
        ('opponentPlayHeuristicsDiffsFunction', 2, 0.2),
        ('opponentPlayHeuristicsDiffsFunction', 1, 0.15),
        ('opponentPlayHeuristicsDiffsFunction', 0.5, 0.11),
        ('opponentPlayHeuristicsDiffsFunction', 0, 0.1),
        ('opponentPlayHeuristicsDiffsFunction', -0.5, 0.1),
        ('opponentPlayHeuristicsDiffsFunction', -1, 0.09),
        ('opponentPlayHeuristicsDiffsFunction', -2, 0.08),
        ('opponentPlayHeuristicsDiffsFunction', -5, 0.06),
        ('opponentPlayHeuristicsDiffsFunction', -10, 0.03),
        ('opponentPlayHeuristicsDiffsFunction', -20, 0.01),
        ('opponentPlayHeuristicsDiffsFunction', -50, 0.005),
        ('opponentPlayHeuristicsDiffsFunction', -100, 0.0005),
        ('opponentPlayHeuristicsDiffsFunction', -500, 0.0001);
