DELETE FROM arg_and_value;

INSERT INTO arg_and_value (function_name, arg, value)
VALUES ('opponentPlayHeuristicsDiffsFunction', 500, 0.9999),
  ('opponentPlayHeuristicsDiffsFunction', 100, 0.9),
  ('opponentPlayHeuristicsDiffsFunction', 50, 0.75),
  ('opponentPlayHeuristicsDiffsFunction', 40, 0.6),
  ('opponentPlayHeuristicsDiffsFunction', 30, 0.48),
  ('opponentPlayHeuristicsDiffsFunction', 20, 0.35),
  ('opponentPlayHeuristicsDiffsFunction', 15, 0.28),
  ('opponentPlayHeuristicsDiffsFunction', 10, 0.23),
  ('opponentPlayHeuristicsDiffsFunction', 8, 0.2),
  ('opponentPlayHeuristicsDiffsFunction', 5, 0.15),
  ('opponentPlayHeuristicsDiffsFunction', 2, 0.12),
  ('opponentPlayHeuristicsDiffsFunction', 1, 0.1),
  ('opponentPlayHeuristicsDiffsFunction', 0.5, 0.08),
  ('opponentPlayHeuristicsDiffsFunction', 0, 0.06),
  ('opponentPlayHeuristicsDiffsFunction', -0.5, 0.06),
  ('opponentPlayHeuristicsDiffsFunction', -1, 0.05),
  ('opponentPlayHeuristicsDiffsFunction', -2, 0.04),
  ('opponentPlayHeuristicsDiffsFunction', -5, 0.02),
  ('opponentPlayHeuristicsDiffsFunction', -10, 0.009),
  ('opponentPlayHeuristicsDiffsFunction', -20, 0.005),
  ('opponentPlayHeuristicsDiffsFunction', -50, 0.001),
  ('opponentPlayHeuristicsDiffsFunction', -100, 0.0001),
  ('opponentPlayHeuristicsDiffsFunction', -500, 0.00001);